export const GET_CHECKOUT_PREVIEW_REQUEST = 'CHECKOUT/GET_CHECKOUT_PREVIEW_REQUEST';
export const GET_CHECKOUT_PREVIEW_SUCCESS = 'CHECKOUT/GET_CHECKOUT_PREVIEW_SUCCESS';
export const GET_CHECKOUT_PREVIEW_FAIL = 'CHECKOUT/GET_CHECKOUT_PREVIEW_FAIL';